# Generated by Django 5.0 on 2026-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("BEAUTY_PRODUCTS", "Beauty Products"),
                    ("CLOTHS", "Cloths"),
                    ("GADGETS", "Gadgets"),
                    ("MOBILES", "Mobiles"),
                ],
                default="BEAUTY_PRODUCTS",
                max_length=40,
            ),
        ),
    ]
