release: python manage.py migrate --noinput && python manage.py shell -c "from django.contrib.auth import get_user_model; User=get_user_model(); User.objects.filter(email='vikramtammisetti@gmail.com').exists() or User.objects.create_superuser('vikramtammisetti@gmail.com','2D@Anime')"
web: gunicorn core.wsgi:application
